### ISSUE TITLE
Enable consecutive setting of ISA object fields by the API

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/ISADotNet#25]
Hi there, i am currently testing this library in a project. There are a few things i have noticed (more issues incoming). The first one is very important imho.

How is this library intended to be used in a script? My naive approach without docs would be trying to build the object hierarchy from the ground up and then writing the whole thing to disk. 

So like:
build my assay(s) -> add them to a study -> add that to an investigation -> save the whole thing to disk.

The very first step is very tedious, partly because of the forced usage of option (but this is already addressed in #24), partly because the parameter order is not pipeline friendly. 

So for example, if i want to set the samples of an empty assay, this has to be done:

```fsharp
let assay = Assay.setMaterials Assay.empty (AssayMaterials.create (Some Samples) None)
```

Note that the assay is the first parameter of `Assay.setMaterials`. I would suggest switching the parameters everywhere, so that the object that gets changed is the last one.
I would like to be able to do something like this:

```fsharp
let assay =
    Assay.empty
    |> Assay.setMaterials(
		Materials.create(
			?OptField1 = ... //ignore second field because i dont know its value by using optional parameters here
		)
	)
    |> Assay.setData(
		Data.create (...)
	)
	...
```

Or am i just not using this as intended? If so, how would it be intended?

**Comment by HLWeil** [comment]
Completely appropriate critique. I thought about this a lot too. Basically there are two general use cases for these functions.
1. Building isa objects/files from scratch (user scripting case). Here you need to manipulate the top level object many times, making your proposed parameter order more practical. 
2. Manipulating existing isa objects/files (ArcCommander case). Here the child object is the item of focus which gets manipulated and the parent object then just gets updated with the new child:
```fsharp
API.Assay.updateByFileName updateOption assay assays
|> API.Study.setAssays study
```

For the second approach, which is the general use case for the `ArcCommander` the parameter order currently used is better, that's why I went for it. I agree though that the quality of life gain for the first use case would be very high if switching the parameter order. 
Do you think the library will be used much in the way you described? If so switching the param order is definitely a possibilit.
